<program> ::= "<?php namespace Example; " <class>
<class> ::= "class Calculator { public static function increment(int $x): int { " <statement-list> " } }"
<statement-list> ::= <statement> <statement-list> | <statement>
<statement> ::= <return>
<return> ::= "return " <expression> ";"
<expression> ::= "(" <operand> <operator> <operand> ")" | <operand>
<operator> ::= "+" | "*"
<operand> ::= "1" | "$x"
