<class> ::= "class Calculator { public function inc(int $x): int { " <return> " } }"
<return> ::= "return " <expression> ";"
<expression> ::= "(" <operand> <operator> <operand> ")" | <operand>
<operator> ::= "+" | "*"
<operand> ::= "1" | "$x"
