<program> ::= "<?php namespace Example; " <class>
<class> ::= "class Calculator { public static function increment($x) { " <statement-list> " } }"
<statement-list> ::= <statement> <statement-list> | <statement>
<statement> ::= <condition> | <return>
<condition> ::= "if (" <boolean-expression> ") {" <statement-list> "}"
<return> ::= "return " <integer-expression> ";"
<integer-expression> ::= "(" <operand> " " <integer-operator> " " <operand> ")" | <operand> | "null"
<integer-operator> ::= "+" | "*"
<boolean-expression> ::= <operand> " " <boolean-operator> " " <operand>
<boolean-operator> ::= "<"
<operand> ::= "0" | "1" | "$x"
